{ pkgs, ... }:

{
  # SwayNC — macOS-style notification center
  # Replaces dunst with a slide-out panel (toggle with SUPER + N)
  # Colors are dynamically generated by pywal via wall-picker
  services.swaync = {
    enable = true;

    settings = {
      positionX = "right";
      positionY = "top";
      layer = "overlay";
      control-center-layer = "top";
      layer-shell = true;
      cssPriority = "application";
      control-center-margin-top = 8;
      control-center-margin-bottom = 8;
      control-center-margin-right = 8;
      control-center-width = 400;
      notification-icon-size = 48;
      notification-body-image-height = 80;
      notification-body-image-width = 200;
      timeout = 8;
      timeout-low = 4;
      timeout-critical = 0;
      fit-to-screen = true;
      notification-window-width = 350;
      keyboard-shortcuts = true;
      image-visibility = "when-available";
      transition-time = 200;

      widgets = [
        "inhibitors"
        "title"
        "dnd"
        "notifications"
      ];

      widget-config = {
        inhibitors = {
          text = "Inhibitors";
          button-text = "Clear";
          clear-all-button = true;
        };
        title = {
          text = "Notifications";
          clear-all-button = true;
          button-text = "Clear All";
        };
        dnd = {
          text = "Do Not Disturb";
        };
      };
    };

    # Empty style — dynamically overwritten by pywal via wall-picker
    # On first boot, swaync uses its built-in default dark theme
    # After picking a wallpaper, wall-picker generates & applies colors-swaync.css
    style = "";
  };
}
