{ pkgs, lib, ... }:

{
  programs.waybar = {
    enable = true;
    systemd.enable = true;
    systemd.target = "hyprland-session.target";

    settings = {
      mainBar = {
        layer = "top";
        position = "top";
        height = 38;
        margin-top = 6;
        margin-left = 8;
        margin-right = 8;
        spacing = 0;

        modules-left = [ "hyprland/workspaces" "hyprland/window" ];
        modules-center = [ "clock" ];
        modules-right = [ "tray" "custom/clipboard" "pulseaudio" "backlight" "network" "bluetooth" "battery" "custom/power" ];

        "hyprland/workspaces" = {
          format = "{icon}";
          format-icons = {
            "1" = "I";
            "2" = "II";
            "3" = "III";
            "4" = "IV";
            "5" = "V";
            active = "";
            default = "";
          };
          on-click = "activate";
          persistent-workspaces = {
            "*" = 5;
          };
        };

        "hyprland/window" = {
          max-length = 35;
          separate-outputs = true;
          rewrite = {
            "" = "Desktop";
          };
        };

        clock = {
          format = "CLK {:%H:%M}";
          format-alt = "CAL {:%a %d %b}";
          tooltip-format = "<tt>{calendar}</tt>";
        };

        battery = {
          format = "BAT {capacity}%";
          format-charging = "CHG {capacity}%";
          format-plugged = "PLG {capacity}%";
          states = {
            warning = 30;
            critical = 15;
          };
          tooltip-format = "{timeTo}";
        };

        network = {
          format-wifi = "NET {essid}";
          format-ethernet = "ETH Wired";
          format-disconnected = "NET Off";
          tooltip-format-wifi = "{essid} ({signalStrength}%)\n{ipaddr}/{cidr}";
          tooltip-format-ethernet = "{ifname}\n{ipaddr}/{cidr}";
          on-click = "networkmanager_dmenu";
        };

        bluetooth = {
          format = "BT";
          format-connected = "BT {device_alias}";
          format-disabled = "BT Off";
          tooltip-format = "{controller_alias}\n{num_connections} connected";
          tooltip-format-connected = "{controller_alias}\n{device_enumerate}";
          tooltip-format-enumerate-connected = "{device_alias}\t{device_battery_percentage}%";
          on-click = "~/.local/bin/bluetooth-menu";
        };

        backlight = {
          format = "BRI {percent}%";
          on-scroll-up = "brightnessctl set +5%";
          on-scroll-down = "brightnessctl set 5%-";
        };

        pulseaudio = {
          format = "VOL {volume}%";
          format-muted = "MUT";
          on-click = "~/.local/bin/volume-menu";
          on-scroll-up = "wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+";
          on-scroll-down = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-";
        };

        "custom/clipboard" = {
          format = "CLP";
          tooltip = false;
          on-click = "cliphist list | rofi -dmenu -p 'Clipboard' -theme-str 'window {width: 40em; border-radius: 12px;} listview {lines: 8; spacing: 4px;} element {padding: 8px 12px; border-radius: 8px;}' | cliphist decode | wl-copy";
        };

        "custom/power" = {
          format = "PWR";
          tooltip = false;
          on-click = "~/.local/bin/power-menu";
        };

        tray = {
          icon-size = 14;
          spacing = 6;
        };
      };
    };

    # Pywal-driven dynamic styling
    # Colors are imported from ~/.cache/wal/colors-waybar.css (generated by pywal)
    # Fallback colors are defined inline for first boot before pywal runs
    style = ''
      @import url("file:///home/batman/.cache/wal/colors-waybar.css");

      * {
        font-family: "JetBrainsMono Nerd Font", "JetBrains Mono", monospace;
        font-size: 13px;
        min-height: 0;
        padding: 0;
        margin: 0;
      }

      window#waybar {
        background: alpha(@background, 0.85);
        border-radius: 12px;
        border: 1px solid alpha(@foreground, 0.08);
      }

      /* --- Left modules --- */
      #workspaces {
        margin: 4px 4px 4px 6px;
        padding: 0;
      }

      #workspaces button {
        padding: 4px 8px;
        margin: 0 2px;
        border-radius: 8px;
        color: alpha(@foreground, 0.5);
        background: transparent;
        transition: all 0.2s ease;
      }

      #workspaces button.active {
        color: @color4;
        background: alpha(@color4, 0.15);
      }

      #workspaces button:hover {
        color: @foreground;
        background: alpha(@foreground, 0.08);
      }

      #window {
        margin: 4px;
        padding: 4px 12px;
        color: alpha(@foreground, 0.6);
      }

      /* --- Center --- */
      #clock {
        margin: 4px;
        padding: 4px 16px;
        border-radius: 8px;
        background: alpha(@color4, 0.15);
        color: @color4;
        font-weight: bold;
      }

      /* --- Right modules (pill-grouped) --- */
      #pulseaudio, #backlight, #network, #bluetooth, #battery, #custom-power, #custom-clipboard, #tray {
        margin: 4px 2px;
        padding: 4px 10px;
        border-radius: 8px;
        color: @foreground;
        background: alpha(@foreground, 0.06);
        transition: all 0.2s ease;
      }

      #pulseaudio:hover, #backlight:hover, #network:hover, #bluetooth:hover, #battery:hover, #custom-power:hover, #custom-clipboard:hover {
        background: alpha(@color4, 0.15);
        color: @color4;
      }

      #custom-power {
        margin-right: 6px;
        color: @color1;
      }

      #custom-power:hover {
        background: alpha(@color1, 0.15);
        color: @color1;
      }

      #battery.warning {
        color: @color3;
      }

      #battery.critical {
        color: @color1;
        animation: blink 1s linear infinite;
      }

      #tray {
        margin-left: 2px;
      }

      @keyframes blink {
        to { color: @foreground; }
      }
    '';
  };
}
